### ISSUE TITLE
Apple M1 chip setup: update "node-sass"

### ISSUE THREAD

**Issue by LorenaEgger** [aleksbobic/csx#97]
**Description**
When running docker-compose up, there's an error with the package "node-sass", which is deprecated and replaced now by "sass". 

**Fix**
In app/package.json  change
"node-sass": "^7.0.0" to "sass": "^1.0.0"

**Comment by aleksbobic** [comment]
Merged request and will close issues. Thank you for your contribution @LorenaEgger ! 😄
